name: Huffman Compression Tests

on:
  push:
    branches: [master, GithubActions]
  pull_request:
    branches: [master, GithubActions]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential g++ make

    - name: Build project
      run: |
        make clean
        make all

    - name: Run tests
      run: |
        cd Tests  # Assuming your test files are in a tests directory
        chmod +x testall.sh
        testall.sh | tee test_output.log

        # Extract test results for GitHub Actions summary
        passed=$(grep "The program passed" test_output.log | grep -o '[0-9]* / [0-9]*')
        echo "## Test Results" >> $GITHUB_STEP_SUMMARY
        echo "Tests passed: $passed" >> $GITHUB_STEP_SUMMARY

    - name: Upload test artifacts on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: test-artifacts
        path: |
          Tests/compressed*.txt
          Tests/extracted*.txt
        retention-days: 7
